'use strict';
const $=id=>document.getElementById(id);let me,posts=[],photo=null,dirty=false,reading=false;
const canvas=$('avatar'),ctx=canvas.getContext('2d');
function avatar(){const color=id=>$(id).value;ctx.clearRect(0,0,400,400);ctx.fillStyle=color('background');ctx.fillRect(0,0,400,400);const ellipse=(x,y,rx,ry,c)=>{ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()};if($('style').value==='long')ellipse(200,195,110,148,color('hair'));ellipse(200,395,155,135,color('shirt'));ctx.fillStyle=color('skin');ctx.fillRect(176,230,48,65);ellipse(200,175,89,108,color('skin'));if($('style').value!=='bald'){ctx.fillStyle=color('hair');ctx.beginPath();ctx.ellipse(200,122,91,64,0,Math.PI,Math.PI*2);ctx.lineTo(285,160);ctx.quadraticCurveTo(195,105,113,162);ctx.fill()}ellipse(166,182,7,9,'#292321');ellipse(234,182,7,9,'#292321');ctx.strokeStyle='#623c30';ctx.lineWidth=5;ctx.beginPath();ctx.arc(200,208,27,.15,Math.PI-.15);ctx.stroke();if($('glasses').checked){ctx.strokeStyle='#222';ctx.lineWidth=6;ctx.strokeRect(139,163,55,38);ctx.strokeRect(207,163,55,38);ctx.beginPath();ctx.moveTo(194,178);ctx.lineTo(207,178);ctx.stroke()}}
function mode(){const upload=document.querySelector('[name=mode]:checked').value==='upload';$('avatarOptions').hidden=upload;$('uploadOptions').hidden=!upload;canvas.hidden=upload;$('preview').hidden=!upload||!photo;dirty=true;}
function render(){
 const list=$('posts');list.replaceChildren();const filtered=posts.filter(p=>$('filter').value==='all'||p.itemType===$('filter').value);
 $('status').textContent=filtered.length?'':'No reports to show.';$('total').textContent=posts.length;
 $('recovered').textContent=posts.filter(p=>p.itemType==='lost'&&['claimed','resolved'].includes(p.itemStatus)).length;
 for(const p of filtered){const card=document.createElement('article');card.className='post';const icon=document.createElement('span');icon.className='post-icon '+(p.itemType==='lost'?'lost':'found');icon.textContent=p.itemType==='lost'?'△':'⌕';icon.setAttribute('aria-hidden','true');const body=document.createElement('div');body.className='post-body';const title=document.createElement('h3');title.textContent=p.title;const meta=document.createElement('p');meta.className='meta';const date=new Date(p.createdAt);meta.textContent=['Reported '+p.itemType,Number.isNaN(date.getTime())?'':date.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}),p.itemID?'#'+p.itemID:''].filter(Boolean).join(' · ');body.append(title,meta);const badge=document.createElement('span');badge.className='badge';badge.dataset.status=p.itemStatus;badge.textContent=p.itemStatus;card.append(icon,body,badge);list.append(card)}
}
function identity(){
 $('name').textContent=me.userName;$('username').textContent=me.userName;$('role').textContent=me.role||'';$('roleValue').textContent=me.role||'';$('roleRow').hidden=!me.role;
 $('emailRow').hidden=!me.email;$('email').textContent=me.email||'';
 const date=new Date(me.createdAt);$('memberSince').textContent=me.createdAt&&!Number.isNaN(date.getTime())?date.toLocaleDateString(undefined,{month:'short',year:'numeric'}):'—';
 if(me.profilePhotoData){$('portrait').src=me.profilePhotoData}else{avatar();$('portrait').src=canvas.toDataURL('image/png')}$('portrait').hidden=false;
 if(me.email){$('navAvatar').src=$('portrait').src;$('navName').textContent=me.userName}
}
function switchTab(people){$('peoplePanel').hidden=!people;$('timelinePanel').hidden=people;$('peopleTab').setAttribute('aria-selected',String(people));$('timelineTab').setAttribute('aria-selected',String(!people))}
$('timelineTab').onclick=()=>switchTab(false);$('peopleTab').onclick=()=>{switchTab(true);$('peopleQuery').focus()};
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{$('filter').value=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render()});
$('logout').onclick=()=>{Auth.logout();location.assign('/login/landing.html')};
$('edit').onclick=()=>{$('displayName').value=me.userName;photo=me.profilePhotoData||null;dirty=false;$('error').textContent='';$('file').value='';document.querySelector('[name=mode][value=upload]').checked=!!photo;document.querySelector('[name=mode][value=avatar]').checked=!photo;if(photo)$('preview').src=photo;mode();dirty=false;$('editor').showModal()};$('cancel').onclick=()=>$('editor').close();document.querySelectorAll('[name=mode]').forEach(el=>el.onchange=mode);$('avatarOptions').oninput=()=>{dirty=true;avatar()};$('filter').onchange=render;
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;$('error').textContent='';photo=null;$('preview').hidden=true;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>4*1024*1024){$('error').textContent='Choose a JPEG, PNG or WebP photo up to 4 MB.';return}reading=true;$('save').disabled=true;let url;try{url=URL.createObjectURL(f);const img=new Image();img.src=url;await img.decode();const c=document.createElement('canvas');c.width=c.height=512;const size=Math.min(img.width,img.height);c.getContext('2d').drawImage(img,(img.width-size)/2,(img.height-size)/2,size,size,0,0,512,512);photo=c.toDataURL('image/jpeg',.9);$('preview').src=photo;$('preview').hidden=false;dirty=true}catch{$('error').textContent='This image could not be opened.'}finally{if(url)URL.revokeObjectURL(url);reading=false;$('save').disabled=false}};
$('profileForm').onsubmit=async e=>{e.preventDefault();if(reading)return;$('error').textContent='';const name=$('displayName').value.trim();if(!name){$('error').textContent='Enter a display name.';return}const upload=document.querySelector('[name=mode]:checked').value==='upload';if(upload&&!photo){$('error').textContent='Choose a photo first.';return}$('save').disabled=true;$('cancel').disabled=true;try{const payload={userName:name};if(dirty||!me.profilePhotoData)payload.profilePhotoData=upload?photo:canvas.toDataURL('image/png');const result=await UserAPI.updateProfile(payload);me={...me,...result.user};localStorage.setItem('asa_user',me.userName);localStorage.setItem('userName',me.userName);identity();$('editor').close();$('status').textContent='Profile saved.'}catch(err){$('error').textContent=err.message||'Could not save profile. Please try again.'}finally{$('save').disabled=false;$('cancel').disabled=false}};

$('savePrivacy').onclick=async()=>{$('savePrivacy').disabled=true;try{await apiFetch('/profiles/settings',{method:'PUT',body:JSON.stringify({showRole:$('showRole').value==='true',timeline:$('timelinePrivacy').value})});$('privacyMessage').textContent='Privacy saved. Changes apply to future profile requests.'}catch(e){$('privacyMessage').textContent=e.message}finally{$('savePrivacy').disabled=false}};
$('findPeople').onsubmit=async e=>{e.preventDefault();switchTab(true);$('peopleResults').textContent='Searching…';try{const people=await apiFetch('/profiles?q='+encodeURIComponent($('peopleQuery').value));$('peopleResults').replaceChildren();for(const person of people){const a=document.createElement('a');a.href='/user/profile.html?id='+person.userID;a.textContent=person.userName;a.style.display='block';$('peopleResults').append(a)}if(!people.length)$('peopleResults').textContent='No profiles found.'}catch(e){$('peopleResults').textContent=e.message}};
(async()=>{if(!Auth.isLoggedIn()){location.replace('/login/landing.html');return}try{const viewer=await UserAPI.getMe();const role=viewer.role.toLowerCase();const path='/user/'+(['student','staff','visitor','admin'].includes(role)?role:'visitor')+'.html';$('home').href=path;$('brand').href=path;$('settings').href=path+'#settings';$('navName').textContent=viewer.userName;if(viewer.profilePhotoData)$('navAvatar').src=viewer.profilePhotoData;else{avatar();$('navAvatar').src=canvas.toDataURL('image/png')}document.querySelectorAll('[data-page]').forEach(a=>a.href=path+'#'+a.dataset.page);$('report').href=path+'#post';const id=new URLSearchParams(location.search).get('id');const own=!id||String(viewer.userID)===id;if(own){me=viewer;identity();$('edit').disabled=false;const privacy=await apiFetch('/profiles/settings');$('showRole').value=String(Boolean(privacy.showRole));$('timelinePrivacy').value=privacy.timeline;$('privacyPanel').hidden=false;posts=await ItemsAPI.getMyPosts();render()}else{$('pageTitle').textContent='Member profile';$('edit').hidden=true;$('report').hidden=true;const data=await apiFetch('/profiles/'+encodeURIComponent(id));me=data.user;posts=data.posts;identity();render();$('privacySummary').textContent='This member chooses which reports appear here.';if(!data.timelineVisible){$('status').textContent='This member keeps their timeline private.';$('total').textContent='Private';$('recovered').textContent='Private';$('filters').hidden=true}}}catch(err){$('name').textContent='Profile unavailable';$('status').textContent=err.message||'Could not load profile.';$('edit').hidden=true;$('report').hidden=true}})();

async function loadProfileNotifications(){try{const notices=await NotifAPI.getAll();const unread=notices.filter(n=>!n.isRead).length;$('notificationCount').textContent=unread;$('notificationCount').hidden=!unread;$('notificationList').replaceChildren();for(const n of notices.slice(0,20)){const button=document.createElement('button');button.textContent=n.message;button.className=n.isRead?'':'unread';button.onclick=async()=>{try{await NotifAPI.markRead(n.notifID);await loadProfileNotifications()}catch{$('notificationList').textContent='Could not mark notification as read.'}};$('notificationList').append(button)}if(!notices.length)$('notificationList').textContent='No notifications yet.'}catch{$('notificationList').textContent='Notifications could not be loaded.'}}
if(Auth.isLoggedIn())loadProfileNotifications();document.querySelector('.notification-menu').addEventListener('toggle',e=>{if(e.currentTarget.open)loadProfileNotifications()});

$('menuToggle').onclick=()=>{const open=$('menuToggle').getAttribute('aria-expanded')!=='true';$('menuToggle').setAttribute('aria-expanded',String(open));$('profileNav').classList.toggle('is-open',open)};
